spring:
  application:
    name: WhereWear
# 파일크기 (10MB)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# AI
  ai:
    google:
      genai:
        api-key: ${GENAI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
# API 버저닝
  mvc:
    apiversion:
      use:
        header: API-Version
# OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
